name: Workflow Dispatch Multiple Input Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true
      notify:
        description: 'Notify of deployment?'
        required: true
        type: boolean
        default: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.environment }} environment"

  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.notify }}
    steps:
      - run: echo "Deployed to ${{ github.event.inputs.environment }}"
